### ISSUE TITLE
"undefined is not an object (evaluating 'history.listen')" error when trying to use "syncHistoryWithStore()" method

### ISSUE THREAD

**Issue by tushar00jain** [reactjs/react-router-redux#367]
I am following all steps mentioned in the docs, using the routerReducer, routerMiddleware and using the provider like so

```javascript
const history = syncHistoryWithStore(browserHistory, store);
render (
	<Provider store={store}>
		<Router history= {history}>
			{routes}
		</Router>
	</Provider>
)
```
but it doesn't seem to work

**Comment by timdorr** [comment]
Make sure you're importing `browserHistory`and have react-router 2.0.

**Comment by dnlek** [comment]
@timdorr I have the same issue using:
react-router@2.2.4
react-router-redux@4.0.2
redux@3.4.0
react-redux@4.4.4

I am using it as follows:

```jsx
import { Router, Route, browserHistory, IndexRoute } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';

let store = configureStore(browserHistory);
const history = syncHistoryWithStore(browserHistory, store);
render(
  <Provider store={store}>
    <div>
      <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={Main} />
        </Route>
      </Router>
    </div>
  </Provider>,
  document.getElementById('app')
);
```

```jsx
export default function configureStore(history, initialState) {
  return createStore(
    combineReducers({
      ...reducers,
      routing: routerReducer,
    }),
    initialState,
    applyMiddleware(
      thunkMiddleware,
      loggerMiddleware,
      routerMiddleware(history)
    )
  );
}
```

and receive the following error:
```
Warning: [react-router] It appears you have provided a deprecated history object to `<Router/>`, please use a history provided by React Router with `import { browserHistory } from 'react-router'` or `import { hashHistory } from 'react-router'`. If you are using a custom history please create it with `useRouterHistory`, see http://tiny.cc/router-usinghistory for details.warning 

Uncaught TypeError: history.listen is not a function
```

**Comment by tushar00jain** [comment]
@dnlek 
I tried using the latest version of react-router also. It seems to work fine with 2.0.1

**Comment by justabuzz** [comment]
Hi @timdorr,

Looks like this is still happening. When I run the app locally using dev server then all good, but after I bundle it then when visiting the page I'm getting "history.listen is not a function".

Here are the package versions I have installed:

├── react@0.14.8
├── react-redux@4.4.5
├── react-router@2.5.1
├── react-router-redux@4.0.5

I'd appreciate any input or suggestion. Happy to supply additional details.

Cheers!

**Comment by justabuzz** [comment]
Hi,

Here's the exact place I see the error - history.listen is not a function:

![image](https://cloud.githubusercontent.com/assets/313585/16608258/49e6554e-438d-11e6-9aeb-e764ce75600a.png)

From what I see this history instance is not instantiated by my code. Looks like it's coming from history module, which is inside react-router's node_modules directory:
node_modules\react-router\node_modules\history\lib\useQueries.js

Cheers.

**Comment by Californian** [comment]
I am also running into this problem. `browserHistory` is imported, and logging the history object within the render function shows an object that is, in fact, without a `listen` function (but its prototype is `History`).

**Comment by timdorr** [comment]
Try deleting your node_modules and reinstalling.

**Comment by justabuzz** [comment]
Hi, just a quick update - I returned to this code a few hours ago and found a typo that caused this. So at least in my case it was a user issue.. :(

Thanks!

**Comment by Californian** [comment]
Yeah I'm pretty sure it's a syntactical issue on my end; I tried simply using `browserHistory` (then, subsequently, `hashHistory`) without `react-router-redux` and it had the same problem, so I moved everything into the same file and it worked (haven't tried with `react-router-redux` again though). I believe it is probably because of an issue similar to the one mentioned in https://github.com/reactjs/react-router/issues/2132#issuecomment-160690510, but I haven't had time to fully debug yet.

**Comment by eldyvoon** [comment]
No solution for this yet?

**Comment by stevenpwalsh05** [comment]
I had this problem, the issue seems to be related to some changes in react-router.  By downgrading from 4.x to 3.x I was able to make this work.

**Comment by IlyaIvanov1** [comment]
react-router@4.0.0 is still broken. Installing 3.0.2 fixes the issue.

**Comment by timdorr** [comment]
react-router-redux 4.0.8 only works with react-router/history 3.x. It doesn't work with the 4.x versions of either library yet.

**Comment by aelmanaa** [comment]
Hello @timdorr ,

thank you very much for the info. Do you have any rough idea when we can expect the react-router-redux to support react-router-dom 4x ? I've tried to use history/createHashHistory but had an issue with time traveling.

thanks a lot

**Comment by ashugit** [comment]
Moving react-router to 3.0.2 helped it work. I was trying to use syncHistoryWithStore with hashHistory after upgrading to react-router 4.0.0. Is the fix available  @timdorr ? Thanks

**Comment by ranjani83** [comment]
still facing the same problem with react-router@4.2.0 and history@4.7.2
